# Generated by Django 3.1 on 2021-01-19 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('url_imagen', models.URLField(validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
